// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             (unknown)
// source: contract.proto

package status

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	StatusAPI_CheckStatus_FullMethodName = "/StatusAPI/CheckStatus"
)

// StatusAPIClient is the client API for StatusAPI service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type StatusAPIClient interface {
	CheckStatus(ctx context.Context, in *CheckStatusRequest, opts ...grpc.CallOption) (*CheckStatusResponse, error)
}

type statusAPIClient struct {
	cc grpc.ClientConnInterface
}

func NewStatusAPIClient(cc grpc.ClientConnInterface) StatusAPIClient {
	return &statusAPIClient{cc}
}

func (c *statusAPIClient) CheckStatus(ctx context.Context, in *CheckStatusRequest, opts ...grpc.CallOption) (*CheckStatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CheckStatusResponse)
	err := c.cc.Invoke(ctx, StatusAPI_CheckStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// StatusAPIServer is the server API for StatusAPI service.
// All implementations must embed UnimplementedStatusAPIServer
// for forward compatibility.
type StatusAPIServer interface {
	CheckStatus(context.Context, *CheckStatusRequest) (*CheckStatusResponse, error)
	mustEmbedUnimplementedStatusAPIServer()
}

// UnimplementedStatusAPIServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedStatusAPIServer struct{}

func (UnimplementedStatusAPIServer) CheckStatus(context.Context, *CheckStatusRequest) (*CheckStatusResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CheckStatus not implemented")
}
func (UnimplementedStatusAPIServer) mustEmbedUnimplementedStatusAPIServer() {}
func (UnimplementedStatusAPIServer) testEmbeddedByValue()                   {}

// UnsafeStatusAPIServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to StatusAPIServer will
// result in compilation errors.
type UnsafeStatusAPIServer interface {
	mustEmbedUnimplementedStatusAPIServer()
}

func RegisterStatusAPIServer(s grpc.ServiceRegistrar, srv StatusAPIServer) {
	// If the following call panics, it indicates UnimplementedStatusAPIServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&StatusAPI_ServiceDesc, srv)
}

func _StatusAPI_CheckStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CheckStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StatusAPIServer).CheckStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StatusAPI_CheckStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StatusAPIServer).CheckStatus(ctx, req.(*CheckStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// StatusAPI_ServiceDesc is the grpc.ServiceDesc for StatusAPI service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var StatusAPI_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "StatusAPI",
	HandlerType: (*StatusAPIServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CheckStatus",
			Handler:    _StatusAPI_CheckStatus_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "contract.proto",
}
