// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             (unknown)
// source: api/v1/contract.proto

package increment

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	IncrementAPI_Inc_FullMethodName = "/IncrementAPI/Inc"
)

// IncrementAPIClient is the client API for IncrementAPI service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type IncrementAPIClient interface {
	Inc(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[IncValue, IncValue], error)
}

type incrementAPIClient struct {
	cc grpc.ClientConnInterface
}

func NewIncrementAPIClient(cc grpc.ClientConnInterface) IncrementAPIClient {
	return &incrementAPIClient{cc}
}

func (c *incrementAPIClient) Inc(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[IncValue, IncValue], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &IncrementAPI_ServiceDesc.Streams[0], IncrementAPI_Inc_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[IncValue, IncValue]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type IncrementAPI_IncClient = grpc.BidiStreamingClient[IncValue, IncValue]

// IncrementAPIServer is the server API for IncrementAPI service.
// All implementations must embed UnimplementedIncrementAPIServer
// for forward compatibility.
type IncrementAPIServer interface {
	Inc(grpc.BidiStreamingServer[IncValue, IncValue]) error
	mustEmbedUnimplementedIncrementAPIServer()
}

// UnimplementedIncrementAPIServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedIncrementAPIServer struct{}

func (UnimplementedIncrementAPIServer) Inc(grpc.BidiStreamingServer[IncValue, IncValue]) error {
	return status.Error(codes.Unimplemented, "method Inc not implemented")
}
func (UnimplementedIncrementAPIServer) mustEmbedUnimplementedIncrementAPIServer() {}
func (UnimplementedIncrementAPIServer) testEmbeddedByValue()                      {}

// UnsafeIncrementAPIServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to IncrementAPIServer will
// result in compilation errors.
type UnsafeIncrementAPIServer interface {
	mustEmbedUnimplementedIncrementAPIServer()
}

func RegisterIncrementAPIServer(s grpc.ServiceRegistrar, srv IncrementAPIServer) {
	// If the following call panics, it indicates UnimplementedIncrementAPIServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&IncrementAPI_ServiceDesc, srv)
}

func _IncrementAPI_Inc_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(IncrementAPIServer).Inc(&grpc.GenericServerStream[IncValue, IncValue]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type IncrementAPI_IncServer = grpc.BidiStreamingServer[IncValue, IncValue]

// IncrementAPI_ServiceDesc is the grpc.ServiceDesc for IncrementAPI service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var IncrementAPI_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "IncrementAPI",
	HandlerType: (*IncrementAPIServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Inc",
			Handler:       _IncrementAPI_Inc_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "api/v1/contract.proto",
}
